name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Python3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install numpy opencv-python
      - name: Run tests
        run: |
          pwd
          ls
          python -u "/home/runner/work/kalmanTracker/kalmanTracker/tests/test_kalmanTracker.py"
